[package]
name = "chaincore"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519 = "2.2.3"
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
hex = "0.4.3"
rand = "0.9.2"
rand_core = { version = "0.6", features = ["std"] }
sha3 = "0.10.8"

[features]